name: CFETS Sentiment Data Collector

on:
  schedule:
    # Beijing Time: 08:46, 10:16, 14:31, 16:01 (UTC minus 8 hours)
    # Only run from Monday to Friday (1-5), weekends may have no data
    - cron: '46 0 * * 1-5'   # UTC 00:46 (Beijing 08:46)
    - cron: '16 2 * * 1-5'   # UTC 02:16 (Beijing 10:16)
    - cron: '31 6 * * 1-5'   # UTC 06:31 (Beijing 14:31)
    - cron: '1 8 * * 1-5'    # UTC 08:01 (Beijing 16:01)
  workflow_dispatch:

env:
  GITHUB_ACTIONS: true

jobs:
  collect-data:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        # cache: 'pip'

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
        echo "Chrome version: $CHROME_VERSION"
        wget -N https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION%.*}
        CHROMEDRIVER_VERSION=$(cat LATEST_RELEASE_${CHROME_VERSION%.*})
        wget -N https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip
        sudo unzip -o chromedriver_linux64.zip -d /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
        chromedriver --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium==4.15.0

    - name: Run CFETS Spider
      run: |
        BEIJING_TIME=$(date -u +%H:%M)
        python -c "import os, sys; sys.path.append(os.getcwd()); from CFETSSentimentSpider import CFETSScheduledSpider; sender_email = os.environ.get('SENDER_EMAIL'); sender_password = os.environ.get('SENDER_PASSWORD'); smtp_server = os.environ.get('SMTP_SERVER'); smtp_port = int(os.environ.get('SMTP_PORT')); spider = CFETSScheduledSpider(); spider.setup_email_config(sender_email=sender_email, sender_password=sender_password, smtp_server=smtp_server, smtp_port=smtp_port); current_time = '$BEIJING_TIME'; print(f'Beijing time: {current_time}'); job_map = {'08:46': spider.job_0846, '10:16': spider.job_1016, '14:31': spider.job_1431, '16:01': spider.job_1601}; job = job_map.get(current_time); print(f'Executing job: {current_time}'); job() if job else (print('No scheduled job for this time, running test mode.') or spider.test_now());"
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}

    - name: Commit and push data
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add sentiment_data_*.json
        if [ -z "$(git diff --cached --name-only)" ]; then
          echo "No new data files to commit"
        else
          git commit -m "Auto-update: CFETS sentiment data for $(date +%Y%m%d)"
          git push
          echo "Data files have been committed and pushed"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
